// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pisstaube.Database;

namespace Pisstaube.Database.Migrations
{
    [DbContext(typeof(PisstaubeDbContext))]
    [Migration("20200524095519_OsuFile")]
    partial class OsuFile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pisstaube.Database.Models.BeatmapSet", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Artist")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Disabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("Favourites")
                        .HasColumnType("bigint");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("HasVideo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RankedStatus")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SetId");

                    b.ToTable("BeatmapSet");
                });

            modelBuilder.Entity("Pisstaube.Database.Models.ChildrenBeatmap", b =>
                {
                    b.Property<int>("BeatmapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Ar")
                        .HasColumnType("float");

                    b.Property<double>("Bpm")
                        .HasColumnType("double");

                    b.Property<float>("Cs")
                        .HasColumnType("float");

                    b.Property<string>("DiffName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("DifficultyRating")
                        .HasColumnType("double");

                    b.Property<string>("File")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FileMd5")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("HitLength")
                        .HasColumnType("bigint");

                    b.Property<float>("Hp")
                        .HasColumnType("float");

                    b.Property<long>("MaxCombo")
                        .HasColumnType("bigint");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<float>("Od")
                        .HasColumnType("float");

                    b.Property<int>("ParentSetId")
                        .HasColumnType("int");

                    b.Property<int>("Passcount")
                        .HasColumnType("int");

                    b.Property<int>("Playcount")
                        .HasColumnType("int");

                    b.Property<int>("TotalLength")
                        .HasColumnType("int");

                    b.HasKey("BeatmapId");

                    b.HasIndex("ParentSetId");

                    b.ToTable("Beatmaps");
                });

            modelBuilder.Entity("Pisstaube.Database.Models.ChildrenBeatmap", b =>
                {
                    b.HasOne("Pisstaube.Database.Models.BeatmapSet", "Parent")
                        .WithMany("ChildrenBeatmaps")
                        .HasForeignKey("ParentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
