// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pisstaube.CacheDb;

namespace Pisstaube.CacheDb.Migrations
{
    [DbContext(typeof(PisstaubeCacheDbContext))]
    [Migration("20200524095951_OsuFile")]
    partial class OsuFile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Pisstaube.CacheDb.Models.Beatmap", b =>
                {
                    b.Property<int>("BeatmapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileMd5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.HasKey("BeatmapId");

                    b.ToTable("CacheBeatmaps");
                });

            modelBuilder.Entity("Pisstaube.CacheDb.Models.CacheBeatmapSet", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastDownload")
                        .HasColumnType("TEXT");

                    b.HasKey("SetId");

                    b.ToTable("CacheBeatmapSet");
                });
#pragma warning restore 612, 618
        }
    }
}
